name: Setup Anbox Cloud
description: |
  Setup Anbox Cloud on a Github runner for running integration tests against
  containerized or virtualized Android instances.

  See https://anbox-cloud.io/docs for more details
inputs:
  channel:
    default: latest/stable
    description: Snap channel of the anbox-cloud-appliance snap to use
    required: false
    type: string
  ubuntu-pro-token:
    default: ''
    description: Ubuntu Pro token to setup access to official image server
    require: false
    type: string

runs:
  using: composite
  steps:
  - name: Attach to Ubuntu Pro
    if: ${{ inputs.ubuntu-pro-token }}
    shell: bash
    run: |
      sudo pro attach ${{ inputs.ubuntu-pro-token }}
      sudo pro enable anbox-cloud --access-only
  - name: Setup LXD
    uses: canonical/setup-lxd@2aa6f7caf7d1484298a64192f7f63a6684e648a4
    with:
      channel: 5.0/stable
  - name: Install necessary snap packages
    shell: bash
    run: |
      sudo snap install --channel=${{ inputs.channel }} anbox-cloud-appliance
  - name: Initialize Anbox Cloud
    shell: bash
    run: |
      anbox-cloud-appliance prepare-node-script | sudo bash -ex

      # FIXME workaround an issue with latest kernel packages which don't
      # seem to update dependency information correctly
      sudo depmod -a

      sudo anbox-cloud-appliance init --auto

      # FIXME Manually allow access for the current user on the CLI as --auto
      # does not do this and --preseed is not working with 1.23.0
      uid="$(id -u)"
      sudo sed -i "s/allowed-uids.*/allowed-uids: [0, $uid]/g" \
        /var/snap/anbox-cloud-appliance/common/ams/server/settings.yaml
      sudo snap restart anbox-cloud-appliance.ams

      # Wait for AMS to be back up
      ready=false
      for (( n=0; n<=5; n++ )); do
        if amc info ; then
          ready=true
          break
        fi
        sleep 5
      done
      if [ "$ready" = false ]; then
        exit 1
      fi